# Generated by Django 5.2.6 on 2026-03-24 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='admins',
            field=models.ManyToManyField(related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
