# Generated by Django 5.2.6 on 2026-03-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='booking',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='maintenancerequest',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='unit',
            managers=[
            ],
        ),
    ]
